services:
    MKebza\SonataExt\Sonata\RoleSecurityHandler:
        arguments:
            $authorizationChecker: "@security.authorization_checker"
            $superAdminRoles:
                - ROLE_SUPER_ADMIN

    MKebza\SonataExt\ActionLog\CurrentUserProvider:
        arguments:
            $tokenStorage: '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'

    MKebza\SonataExt\Block\CronMonitorBlock:
        tags:
            - { name: 'sonata.block' }

    MKebza\SonataExt\Repository\ActionLogRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags:
            - { name: 'doctrine.repository_service' }

    ####################################################################################################################
#    MKebza\SonataExt\DataFixture\Processor\UserProcessor:
#        tags:
#            - { name: 'the' }

    ####################################################################################################################
    # Commands
    MKebza\SonataExt\Command\RoleExportCommand:
        tags:
            - { name: 'console.command' }

    ####################################################################################################################
    # Events

    # FOS User bundle
    MKebza\SonataExt\EventListener\FOSUser\RedirectSubscriber:
        arguments:
            $router: "@router"
        tags:
            - { name: kernel.event_subscriber }


    # Action log
    MKebza\SonataExt\EventListener\ActionLog\CreateLoggableRelationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    MKebza\SonataExt\EventListener\ActionLog\InjectUserSubscriber:
        arguments:
            $userProvider: '@MKebza\SonataExt\ActionLog\CurrentUserProvider'
        tags:
            - { name: doctrine.orm.entity_listener }

    # Sonata
    MKebza\SonataExt\EventListener\Sonata\MenuDashboardSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # Others
    MKebza\SonataExt\EventListener\CommandInfoSubscriber:
        arguments:
            $stopwatch: '@Symfony\Component\Stopwatch\Stopwatch'
        tags:
            - { name: kernel.event_subscriber }



    ####################################################################################################################
    # Forms
    MKebza\SonataExt\Form\Type\User\UserSecurityRolesType:
        tags:
            - { name: form.type }
        arguments:
            $roles: '%security.role_hierarchy.roles%'
            $decisionManager: '@Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface'

    MKebza\SonataExt\Form\Type\UserGroup\UserGroupSecurityRolesType:
       tags:
           - { name: form.type }
       arguments:
           $roles: '%security.role_hierarchy.roles%'


    MKebza\SonataExt\Form\Type\TemplateType:
        tags:
            - { name: form.type }

