services:
    MKebza\SonataExt\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MKebza\SonataExt\Sonata\RoleSecurityHandler:
        arguments:
            $authorizationChecker: "@security.authorization_checker"
            $superAdminRoles:
                - ROLE_SUPER_ADMIN

    MKebza\SonataExt\ActionLog\CurrentUserProvider:
        arguments:
            $tokenStorage: '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'

    MKebza\SonataExt\Block\CronMonitorBlock:
        tags:
            - { name: 'sonata.block' }

    MKebza\SonataExt\Repository\ActionLogRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags:
            - { name: 'doctrine.repository_service' }


    MKebza\SonataExt\Service\AppMailer:
        arguments:
            $fromName: 'Test'
            $fromEmail: 'info@test.com'
            $mailer: '@mailer'
            $translator: '@translator'
            $templating: '@templating'


    ####################################################################################################################
#    MKebza\SonataExt\DataFixture\Processor\UserProcessor:
#        tags:
#            - { name: 'the' }

    # Timestampable
    MKebza\SonataExt\EventListener\Timestampable\TimestampableSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    ####################################################################################################################
    # Security
    MKebza\SonataExt\DataFixture\Processor\UserProcessor:
        arguments:
            $encoder: '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface'
        tags:
            - { name: 'fidry_alice_data_fixtures.processor' }

    MKebza\SonataExt\Security\UserChangePassword:
        arguments:
            $encoder: '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface'
            $dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
            $em: '@Doctrine\ORM\EntityManagerInterface'


    ####################################################################################################################
    # Commands
    MKebza\SonataExt\Command\RoleExportCommand:
        tags:
            - { name: 'console.command' }

    ####################################################################################################################
    # Action log
    MKebza\SonataExt\EventListener\ActionLog\CreateLoggableRelationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    MKebza\SonataExt\EventListener\ActionLog\InjectUserSubscriber:
        arguments:
            $userProvider: '@MKebza\SonataExt\ActionLog\CurrentUserProvider'
        tags:
            - { name: doctrine.orm.entity_listener }

    # Sonata
    MKebza\SonataExt\EventListener\Sonata\MenuDashboardSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # Others
    MKebza\SonataExt\EventListener\CommandInfoSubscriber:
        arguments:
            $stopwatch: '@Symfony\Component\Stopwatch\Stopwatch'
        tags:
            - { name: kernel.event_subscriber }



    ####################################################################################################################
    # Forms
    MKebza\SonataExt\Form\Type\UserGroup\UserGroupSecurityRolesType:
       tags:
           - { name: form.type }
       arguments:
           $roles: '%security.role_hierarchy.roles%'


    MKebza\SonataExt\Form\Type\TemplateType:
        tags:
            - { name: form.type }

