services:
    sonata.admin.action_log:
        class: MKebza\SonataExt\Admin\ActionLogAdmin
        arguments: [~, MKebza\SonataExt\Entity\ActionLog, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: true, group: 'System', label: 'Log', icon: '<i class="fa fa-gears"></i>'}
