services:
    sonata.admin.log:
        class: MKebza\SonataExt\Admin\LogAdmin
        arguments: [~, MKebza\SonataExt\Entity\Log, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: true, group: 'System', label: 'Log', icon: '<i class="fa fa-gears"></i>'}
