services:
    # Admin definitions
    sonata.admin.user_group:
        class: MKebza\SonataExt\Admin\UserGroupAdmin
        arguments: [~, App\Entity\UserGroup, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: true, group: 'Users', label: 'Groups'}
