services:
    sonata.admin.user:
        class: MKebza\SonataExt\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        calls:
            - ['addChild', ['@sonata.admin.user.log', 'reference']]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                show_in_dashboard: true
                group: 'menu.group.users'
                label: 'menu.item.users'
                icon: '<i class="fa fa-users"></i>'

    sonata.admin.user.log:
        class: MKebza\SonataExt\Admin\LogReferenceAdmin
        arguments: [~, MKebza\SonataExt\Entity\UserLog, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
