<?php

/*
 * Author: (c) Marek Kebza <marek@kebza.cz>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

declare(strict_types=1);

namespace MKebza\SonataExt\Entity;

use Doctrine\ORM\Mapping as ORM;
use MKebza\SonataExt\ORM\SonataExtUserGroupInterface;

/**
 * @ORM\Entity()
 */
class UserGroupLog extends LogReference
{
    /**
     * @ORM\ManyToOne(targetEntity="MKebza\SonataExt\ORM\SonataExtUserGroupInterface", inversedBy="log")
     */
    protected $reference;

    public static function getDiscriminatorEntryName(): string
    {
        return 'user_group';
    }

    /**
     * @return SonataExtUserGroupInterface
     */
    public function getReference(): object
    {
        return parent::getReference(); // TODO: Change the autogenerated stub
    }

    /**
     * @param SonataExtUserGroupInterface $reference
     *
     * @return LogReference
     */
    public function setReference(object $reference): LogReference
    {
        return parent::setReference($reference); // TODO: Change the autogenerated stub
    }
}
