<?php

/*
 * Author: (c) Marek Kebza <marek@kebza.cz>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace MKebza\SonataExt\Admin;

use App\Entity\User;
use Knp\Menu\ItemInterface;
use MKebza\SonataExt\Entity\UserLog;
use MKebza\SonataExt\Service\Logger\AdminLoggerTab;
use Rollerworks\Component\PasswordStrength\Validator\Constraints\PasswordRequirements;
use Sonata\AdminBundle\Admin\AdminInterface;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserAdmin extends AbstractAdmin
{
    use AdminLoggerTab;

    protected $baseRoutePattern = 'user';
    protected $baseRouteName = 'admin_user';

    public function getFormBuilder()
    {
        $this->formOptions['validation_groups'] = (!$this->getSubject() || null === $this->getSubject()->getId()) ? 'Registration' : 'Profile';

        return parent::getFormBuilder();
    }

    public function preUpdate($object)
    {
        parent::preUpdate($object); // TODO: Change the autogenerated stub

        $this->getConfigurationPool()->getContainer()->get('monolog.logger.action')->error('Muj super error', ['references' => $object]);
    }

    protected function configureSideMenu(ItemInterface $menu, $action, AdminInterface $childAdmin = null)
    {
        if (!$childAdmin && !in_array($action, ['edit', 'show'], true)) {
            return;
        }

        $em = $this->getConfigurationPool()->getContainer()->get('doctrine');

//        dd($em->getManagerForClass(UserLog::class));

        $currentAdmin = $this->getCurrentLeafChildAdmin();
        $admin = $this->isChild() ? $this->getParent() : $this;
        $id = $admin->getRequest()->get('id');
        $childId = $admin->getRequest()->get('childId');

        $menu
                ->addChild('Log', [
                    'route' => 'admin_user_reference_list',
                    'routeParameters' => ['id' => $id],
                ])
                ->setAttribute('icon', 'fa fa-bars');
    }

    protected function configureFormFields(FormMapper $form)
    {
        parent::configureFormFields($form);

        $this->tabGeneral($form);
        $form->tab('Security')
                ->with('Status')
                    ->add('active')
//                    ->add('plainPassword', PasswordType::class)
                ->end();

        if ($this->isGranted('ROLE_ADMIN_GRANT_PERMISSION')) {
            $form
                ->with('Groups')
                    ->add('groups', null, [
                        'multiple' => true,
                        'expanded' => true,
                    ])
                ->end()
            ;
        }

        $form->end();

//        $this->tabLog($form);
    }

    protected function tabGeneral(FormMapper $form): void
    {
        $form
            ->tab('User')
                ->with('General')
                    ->add('email');

        if (null === $this->id($this->getSubject())) {
            $form->add('password', null, [
                'mapped' => false,
                'constraints' => [
                    new NotBlank(),
                    new PasswordRequirements([
                        'requireCaseDiff' => true,
                        'requireNumbers' => true,
                        'minLength' => 10,
                    ]),
                ],
            ]);
        }

        $form
                ->end()
            ->end();
    }

    protected function configureListFields(ListMapper $list)
    {
        parent::configureListFields($list);

        $actions = ['edit' => []];

        if ($this->isGranted('ROLE_ALLOW_IMPERSONATE')) {
            $actions['switch'] = ['template' => ['@SonataExt/user/list/action_impersonate.html.twig']];
        }

        $actions['delete'] = [];

        $list
            ->addIdentifier('email', 'string', ['label' => 'User.field.email'])
            ->add('active', 'boolean', ['label' => 'User.field.active', 'editable' => true])
            ->add('created', 'date', ['label' => 'User.field.created'])
            ->add('_action', null, ['actions' => $actions]);
    }
}
